name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.flags.outputs.deploy }}
    steps:
      - id: flags
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ contains(join(github.event.commits.*.message), '#skip') }}" == "false" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run eslint

      - name: Run unit tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

  deploy:
      if: ${{ needs.configure.outputs.deploy == 'true' }}
      needs: [configure, build_and_test]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  version_and_tag:
    needs: [deploy]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify:
    if: ${{ (success() || failure()) && needs.configure.outputs.deploy == 'true' }}
    needs: [configure, build_and_test, deploy, version_and_tag]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
